spring:
  cloud:
    discovery:
      enabled: true
    netflix:
      eureka:
        client:
          serviceUrl:
            defaultZone: { HOST-EUREKA }

  application:
    name: data-retriever
    redis:
      host: { HOST_REDIS }
      port: { PORT-REDIS }
      client-type: lettuce
data-retriever:
  rest:
    base-path: /api/movie
    get-movie: /{id}
    get-movies: /all
    search: /find
  config:
    client:
      name: API-OPERATOR
      movie:
        operation:
          find-all: /api/movie/all
          find-id: /api/movie/{id}
          search: /api/movie/find
