server:
  port: 8084
spring:
  cloud:
    discovery:
      enabled: true
    netflix:
      eureka:
        client:
          serviceUrl:
            defaultZone: ${EUREKA}

  application:
    name: data-retriever
  data:
    redis:
      host: ${REDISHOST}
      port: ${REDISPORT}
      client-type: lettuce
      username: ${REDISUSER}
      password: ${REDISPASSWORD}
data-retriever:
  rest:
    base-path: /api/movie
    get-movie: /{id}
    get-movies: /all
    search: /find
  config:
    client:
      name: API-OPERATOR
      movie:
        operation:
          find-all: /api/movie/all
          find-id: /api/movie/{id}
          search: /api/movie/find
