server:
  port: 8084
spring:
  cloud:
    discovery:
      enabled: true
  application:
    name: data-retriever
  data:
    redis:
      host: ${REDISHOST}
      port: ${REDISPORT}
      username: ${REDISUSER}
      password: ${REDISPASSWORD}
      client-type: lettuce
      ssl:
        enabled: true
      connect-timeout: 5000
data-retriever:
  rest:
    host: https://api-operator-production.up.railway.app
    base-path: /api/movie
    get-movie: /{id}
    get-movies: /all
    search: /find
  config:
    client:
      name: API-OPERATOR
      movie:
        operation:
          find-all: /api/movie/all
          find-id: /api/movie/{id}
          search: /api/movie/find
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA}
